# ==========================================
# MQ Benchmarker - Server Configuration
# ==========================================

# Web Server Port for the UI
server.port=8080

# (Optional) Log level changes
spring.main.banner-mode=off
logging.level.org.springframework=WARN
logging.level.org.apache.activemq=WARN
logging.level.org.apache.qpid=WARN
logging.level.org.apache.activemq.artemis.core.client=ERROR