# Web Server
server.port=8080

# 1. Broker Configuratie (Default)
spring.artemis.broker-url=tcp://mqart01.mqlabs.io:61616
spring.artemis.user=admin
spring.artemis.password=admin

# 2. Connection Pool (Voorbereid op 1000+ verbindingen)
spring.artemis.pool.enabled=true
benchmark.pool.max-connections=1000
benchmark.pool.max-sessions-per-connection=500

# TLS Voorbereiding
# spring.artemis.broker-url=tcp://mqart01.mqlabs.io:61616?sslEnabled=true
# spring.artemis.properties.trustStore=/app/certs/truststore.jks
# spring.artemis.properties.trustStorePassword=geheim